apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-drk1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-drk1
    app.kubernetes.io/part-of: tkrw-pr714-0075-0025-app
  name: devfile-sample-drk1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-drk1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-drk1
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0025-tenant/tkrw-pr714-0075-0025-app/devfile-sample-drk1@sha256:b96492877e765e4359ccffe824a03ea5ed2b3d515036777197d2af5d452c8355
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
